name: ACE Parking Monitor

on:
  # Run every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      force_notification:
        description: 'Force send test notification'
        required: false
        type: boolean
        default: false

# Permissions for artifact upload and repo write
permissions:
  contents: write
  actions: write

jobs:
  check-parking:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    # Set up Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # Cache dependencies for faster runs
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Install Playwright browsers
    - name: Install Playwright browsers
      run: |
        playwright install chromium
        playwright install-deps chromium
    
    # Download previous state (if exists)
    - name: Download previous state artifact
      uses: actions/download-artifact@v3
      with:
        name: parking-state
        path: data/
      continue-on-error: true
    
    # Run the parking monitor
    - name: Check parking availability
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        FORCE_NOTIFICATION: ${{ github.event.inputs.force_notification }}
      run: |
        python -m src.scraper
    
    # Upload state as artifact for next run
    - name: Upload state artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: parking-state
        path: data/last_state.json
        retention-days: 1
    
    # Commit state back to repo (alternative persistence method)
    - name: Commit state changes
      if: always()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/last_state.json || true
        git diff --quiet && git diff --staged --quiet || git commit -m "Update parking state [skip ci]"
        git push || true
      continue-on-error: true
    
    # Log results
    - name: Check logs
      if: failure()
      run: |
        echo "Monitor failed. Check logs above for details."
        ls -la data/ || true
        cat data/last_state.json || true